### ISSUE TITLE
[seo-check]: Error: Starting a new rule when there are errors that haven't been added to results. 

### ISSUE THREAD

**Issue by kiuKisas** [Elderjs/plugins#116]
During the build, I'm having these error that I didn't have in the previous version of seo-check. I don't have time to investigate today so I post it here and I will dig more in the next days.

Full log taht appears several times in a row:
```
Error: Starting a new rule when there are errors that haven't been added to results. Did you run 'finishRule'?
    at startRule (/home/equinox/Programming/opo/website/node_modules/@nickreese/seo-lint/build/Tester.js:114:19)
    at test (/home/equinox/Programming/opo/website/node_modules/@nickreese/seo-lint/build/Tester.js:171:17)
    at Object.folder (/home/equinox/Programming/opo/website/node_modules/@nickreese/seo-lint/build/Tester.js:219:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.run (/home/equinox/Programming/opo/website/node_modules/@elderjs/plugin-seo-check/index.js:72:40)
    at async Object.run (/home/equinox/Programming/opo/website/node_modules/@elderjs/elderjs/build/plugins/index.js:111:44)
    at async /home/equinox/Programming/opo/website/node_modules/@elderjs/elderjs/build/utils/prepareRunHook.js:46:44
    at async Elder.processHook [as runHook] (/home/equinox/Programming/opo/website/node_modules/@elderjs/elderjs/build/utils/prepareRunHook.js:41:13)
    at async build (/home/equinox/Programming/opo/website/node_modules/@elderjs/elderjs/build/build/build.js:207:13)
    ```

**Comment by nickreese** [comment]
Hmm. Seems like an internal error. Any more examples of how to make it happen? I’m nof seeing it on my end. Will be using that plugin extensively next week.

**Comment by kiuKisas** [comment]
It was an internal error indead, that I found by checking the log. In my case, the "true" error was hidden to me by too many error from seo-check. Not a priority, but if we can do something about it it can be great :)

**Comment by flauc** [comment]
Looks like it's line 97 in rules.js in my case `TypeError: Cannot read property 'length' of undefined`

```
tester.test(90, assert_1.default.notStrictEqual, metas[0].content.length, 0, 'Meta description should not be empty');
```

Maybe I have a meta element without a content attribute somewhere or something like that.
