### ISSUE TITLE
@elderjs/plugin-images - Incorrectly resolved rootDir and images not copied to ./public/images

### ISSUE THREAD

**Issue by dmitrysmagin** [Elderjs/plugins#150]
I noticed on Windows the plugin breaks on copying the images from /images to /public/images.
The fix is trivial: use plugin.crossPlatformRoot instead of plugin.settings.rootDir (because it has windows backslash instead of forward slash)

![image](https://user-images.githubusercontent.com/2268825/159276216-e25caaf8-4651-4560-b579-8bdfca1cf7c2.png)

The initial error looks like:
elderjs-plugin-images: Processing 1 local source images.
Error: ENOENT: no such file or directory, copyfile 'C:/Users/user/src/elderjs-app/images/test.jpg' -> 'C:\Users\user\src\elderjs-app\public\images\images\test.jpg'
    at Object.copyFileSync (fs.js:1907:3)
    at processImages (C:\Users\user\src\elderjs-app\src\plugins\plugin-images\index.js:69:14)
    at Object.run (C:\Users\user\src\elderjs-app\src\plugins\plugin-images\index.js:363:35)
    at Object.run (C:\Users\user\src\elderjs-app\node_modules\@elderjs\elderjs\build\plugins\index.js:112:55)
    at C:\Users\user\src\elderjs-app\node_modules\@elderjs\elderjs\build\utils\prepareRunHook.js:46:55
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Elder.processHook [as runHook] (C:\Users\user\src\elderjs-app\node_modules\@elderjs\elderjs\build\utils\prepareRunHook.js:41:13)
    at async C:\Users\user\src\elderjs-app\node_modules\@elderjs\elderjs\build\Elder.js:169:17 {
  errno: -4058,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: 'C:/Users/user/src/elderjs-app/images/test.jpg',
  dest: 'C:\\Users\\user\\src\\elderjs-app\\public\\images\\images\\test.jpg'
}

**Comment by nickreese** [comment]
@dmitrysmagin Thanks. Will be fixed next release.
