### ISSUE TITLE
helpers.picture is not a function

### ISSUE THREAD

**Issue by BetaConnector** [Elderjs/plugins#64]
Hey,

I insstalled the plugin via npm and added the full configuration to elder.config.js.

I am trying to place the picture directly into my svelte-Route-File:
```js
{@html helpers.picture("images/ecommerce.jpg", {maxWidth: 200, class:'', alt: ''})}
```
Roll up prompts the following error:
`  TypeError: helpers.picture is not a function
      at /home/alex/Docker/Projekte/netadvising_new/___ELDER___/compiled/routes/Homepage.js:33:140
      at Object.each (/home/alex/Docker/Projekte/netadvising_new/___ELDER___/compiled/index-20d95f96.js:1323:16)
      at /home/alex/Docker/Projekte/netadvising_new/___ELDER___/compiled/routes/Homepage.js:33:13
      at $$render (/home/alex/Docker/Projekte/netadvising_new/___ELDER___/compiled/index-20d95f96.js:1357:22)
      at render (/home/alex/Docker/Projekte/netadvising_new/___ELDER___/compiled/index-20d95f96.js:1365:26)
      at Object.templateComponent (/home/alex/Docker/Projekte/netadvising_new/node_modules/@elderjs/elderjs/build/utils/svelteComponent.js:41:44)
      at buildPage (/home/alex/Docker/Projekte/netadvising_new/node_modules/@elderjs/elderjs/build/utils/Page.js:43:40)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Object.run (/home/alex/Docker/Projekte/netadvising_new/node_modules/@elderjs/elderjs/build/hooks/index.js:81:34)
      at async /home/alex/Docker/Projekte/netadvising_new/node_modules/@elderjs/elderjs/build/utils/prepareRunHook.js:45:44,
  Error: Hook: "elderProcessShortcodes" threw an error: Cannot find source image with /images/ecommerce.jpg
      at Object.picture (/home/alex/Docker/Projekte/netadvising_new/node_modules/@elderjs/plugin-images/utils/imageStore.js:57:17)
      at Object.run (/home/alex/Docker/Projekte/netadvising_new/node_modules/@elderjs/plugin-images/index.js:171:34)
      at Object.<anonymous> (/home/alex/Docker/Projekte/netadvising_new/node_modules/@elderjs/elderjs/build/utils/prepareShortcodeParser.js:18:55)
      at ShortcodeParser.parsers.process (/home/alex/Docker/Projekte/netadvising_new/node_modules/@elderjs/shortcodes/lib/parser.js:276:59)
      at Tokenizer.tokenize (/home/alex/Docker/Projekte/netadvising_new/node_modules/@elderjs/shortcodes/lib/tokenizer.js:251:31)
      at ShortcodeParser.parse (/home/alex/Docker/Projekte/netadvising_new/node_modules/@elderjs/shortcodes/lib/parser.js:45:19)
      at Object.run (/home/alex/Docker/Projekte/netadvising_new/node_modules/@elderjs/elderjs/build/hooks/index.js:115:48)
      at /home/alex/Docker/Projekte/netadvising_new/node_modules/@elderjs/elderjs/build/utils/prepareRunHook.js:45:55
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Page.processHook [as runHook] (/home/alex/Docker/Projekte/netadvising_new/node_modules/@elderjs/elderjs/build/utils/prepareRunHook.js:40:13)`

I did a console output on the helpers opject and it shows me the following:
```js
{
  permalinks: {
    blog: [Function (anonymous)],
    cms: [Function (anonymous)],
    homepage: [Function (anonymous)]
  },
  inlineSvelteComponent: [Function: inlineSvelteComponent],
  shortcode: [Function (anonymous)],
  images: {
    src: [Function: src],
    largest: [Function: largest],
    picture: [Function: picture]
  }
}
```
According to the documentation, the helper should be be heaving a picture-function:
```js
{@html helpers.picture("images/ecommerce.jpg", {maxWidth: 200, class:'', alt: ''})}
```
Is the documentation outdated or am I missing something?

edit:
When changing the folder to /images/* (star is missing in part of the documentation) I am able to render the pictures with
```js
{@html helpers.shortcode({name: 'picture',  props: { src: "/images/ecommerce.jpg", maxWidth: 200, class:'', alt: '' }})}
```
Should this also work?:
```js
{@html helpers.picture("images/ecommerce.jpg", {maxWidth: 200, class:'', alt: ''})}
```
Thanks in advanced,

Alex

**Comment by nickreese** [comment]
@BetaConnector Looks like there is a typo in the docs. `helpers.images.picture` should do it.

**Comment by BetaConnector** [comment]
@nickreese, thanks  a lot - worked fine...
